const CustomImage = {
    back: require("../../assets/back.png"),
    location: require("../../assets/location.png"),
    home: require("../../assets/home.png"),
    MyTeam: require("../../assets/MyTeam.png"),
    Categories: require("../../assets/Categories.png"),
    LocalVendor: require("../../assets/LocalVendor.png"),
    MyOffer: require("../../assets/MyOffer.png"),
    product: require("../../assets/product.png"),
    delete: require("../../assets/delete.png"),
    card: require("../../assets/card.png"),
    truck: require("../../assets/truck.png"),
    refund: require("../../assets/refund.png"),
    priority: require("../../assets/priority.png"),
    exclusive: require("../../assets/exclusive.png"),
    fashion: require("../../assets/fashion.png"),
    grocery: require("../../assets/grocery.png"),
    note: require("../../assets/note.png"),
    MBOffer: require("../../assets/MBOffer.jpeg"),
    MBOffer2: require("../../assets/MBOffer2.jpeg"),
    MBOffer3: require("../../assets/MBOffer3.jpeg"),
    heart: require("../../assets/heart.png"),
    user: require("../../assets/user.png"), user2: require("../../assets/user2.png"),
    drawer: require("../../assets/drawer.jpg"),
    account: require("../../assets/account.png"),
    subscription: require("../../assets/subscription.png"),
    allOffers: require("../../assets/allOffers.png"),
    customer: require("../../assets/customer.png"),
    guide: require("../../assets/guide.png"),
    logout: require("../../assets/logout.png"),
    order: require("../../assets/order.png"),
    filter: require("../../assets/filter.png"),
    go: require("../../assets/go.png"),
    camera: require("../../assets/camera.png"),
    gallery: require("../../assets/gallery.png"),
    right: require("../../assets/right.png"),
    birthday: require("../../assets/birthday.png"),
    email: require("../../assets/email.png"),
    edit: require("../../assets/edit.png"),
    call: require("../../assets/call.png"),
    findproduct: require("../../assets/findproduct.png"),
    store: require("../../assets/store.png"),
    address: require("../../assets/address.png"),
    payment: require("../../assets/payment.png"),
    start: require("../../assets/start.png"),

    b1: require("../../assets/b1.webp"),
    b2: require("../../assets/b2.jpg"),
    b3: require("../../assets/b3.png"),
    b4: require("../../assets/b4.png"),

}
export default CustomImage;